Реализация ТЗ спринта 9
AleksKras/java-filmorate pull request #1
Opened 2022-08-13 16:16 UTC by AleksKras

2022-08-14 10:46 UTC, Frilock requested changes
Добрый день, написал ряд комментариев к работе. Жду новую итерацию.

2022-08-14 10:46 UTC, Frilock commented on pom.xml
> +			<version>1.18.20</version>
Версии библиотек, которые вы подключаете в pom файле, правильнее писать в preporties (по аналогии с версией java), поскольку pom файлы могут быть очень большого размера и изменение версии библиотеки может оказаться не такой простой задачей.

2022-08-14 10:46 UTC, Frilock commented on pom.xml
> +			<version>2.8.8</version>
Аналогично

2022-08-14 10:46 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
Чтобы над каждым методом в маппинге не писать "/films", можете над контроллером поставить RequestMapping("/films")

2022-08-14 10:46 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
Вообще оба контроллера имеют много общего, как вариант Вы можете сделать абстрактный класс и общие методы вынести туда.

2022-08-14 10:46 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Получен Put запрос к эндпоинту: /films");
три строчки с логом можете в одну обьединить)

2022-08-14 10:46 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Пользователь с ID=" + filmId + "не найден");
перед не найден пробел - сольется иначе

2022-08-14 10:46 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTest.java
> +    void ShouldCreateFilmWithWrongReleaseDate() {
Название методов в Java с маленькой буквы.

2022-08-14 10:46 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTest.java
> +    void ShouldCreateFilmWithWrongDescription() {
Если сложно уместить описание теста в названии, можете воспользоваться аннотацией DisplayName("кратко что делает тест")

2022-08-14 10:46 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
лучше строчку пропустить перед private int id

2022-08-14 10:46 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void validate() {
Такую логику валидации лучше перенести в контроллер. Класс Film это класс модели данных, тут должны быть только поля

2022-08-14 10:46 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String login;
Еще нужно проверить что поле будет != null и != "    "
Можете воспользоваться аннотацией pattern и вставить туда регулярное выражение

2022-08-14 18:36 UTC, AleksKras commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Пользователь с ID=" + filmId + "не найден");
не понимаю замечание. пробелы добавила Idea после нажатия ctrl+alt+L

2022-08-14 19:02 UTC, AleksKras commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String login;
проверил. при @NotBlank не пропускает null и " "

2022-08-15 05:44 UTC, Frilock approved these changes
Принято, но есть комментарии к работе. В следующем спринте поправьте пожалуйста

2022-08-15 05:44 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +abstract class Controller <T>{
Лучше более детально назвать FilmorateAbstractController может быть так

2022-08-15 05:44 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +        log.info("Получен GET запрос");
А почему в одну строчку лог не пишете?)

2022-08-15 05:44 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +    protected List<T> findAll() {
Методы create и update тоже можно было бы сюда перенести

2022-08-15 05:44 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping()
() не нужны

2022-08-15 05:44 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmValidationTest.java
> +    @DisplayName("Тест валидации неправльного Name")
опечатка в слове неправильного

2022-08-21 14:37 UTC, merged