Add friends likes
AleksKras/java-filmorate pull request #2
Opened 2022-08-25 19:18 UTC by AleksKras

2022-08-26 13:53 UTC, Frilock requested changes
Добрый день, работу выполнили хорошо, оставил ряд мелких комментариев, где на мой взгляд, можно лучше.

2022-08-26 13:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    private final String error;
Зачем создавать структуру из одного поля? Почему просто строку не использовать?

2022-08-26 13:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private HashSet<Integer> friends;
Для идентификаторов правильнее было бы использовать Long, вдруг у вас будет очень много записей

2022-08-26 13:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService) {
Чтобы не создавать такой конструктор, можете воспользоваться аннотацией на класс от lombok - requairedArgsConstructor. Это не призыв к действию, но вдруг не знали.

2022-08-26 13:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public List<Film> getPopularFilms(int count) {
А почему Set не используете? Могут ли фильмы повторяться?

2022-08-26 13:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +
Лишняя пустая строка

2022-08-26 13:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +@Component
Над интерфейсами лучше не ставить аннотации для бинов (component, controller, service..). Ставьте лучше только над реализациями

2022-08-26 13:53 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +public interface UserStorage {
Кстати у вас в обоих интерфейсах для Storage повторяются все методы, можете абстрактный класс реализовать =)

2022-08-28 13:09 UTC, AleksKras commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +public interface UserStorage {
т.к. сущности все-таки разные, при развитии проекта может поменяться логика работы для фильмов и пользователей. считаю что абстрактный класс здесь делать рано, как минимум из-за того что не известно какие требования в дальнейших заданиях.

2022-08-28 13:10 UTC, AleksKras commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService) {
Не понимаю тогда как указать аннотацию autowired к такому конструктору.

2022-08-28 19:24 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserService userService) {
А не надо указывать аннотацию Autowired, если у класса, который помечен, как бин спринга (component, service, repository, controller) один конструктор, спринг сам заавтовайрид зависимости и явно аннотацию ставить не нужно. То есть если вы со своего конструктора уберете аннотацию, то у вас все будет работать

2022-08-28 19:27 UTC, Frilock approved these changes
Принято

2022-08-28 19:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +            commonFriends = (HashSet<Long>) friendFriends.clone();
Вообще лучше addAll использовать

2022-08-28 19:27 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Можно было абстрактный класс сделать для FilmStorage и UserStorage методы то по сути одинаковые.

2022-09-17 10:46 UTC, merged